version: '3.9'

services:

  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      DISABLE_ACCESS_LOGS: false
    volumes:
      # - conf:/etc/nginx/conf.d
      - ./conf.d:/etc/nginx/conf.d
      #      - ./conf.d/rate_limit.conf:/etc/nginx/conf.d/rate_limit.conf:ro # only 1 file
      # - vhost:/etc/nginx/vhost.d
      - ./vhost.d:/etc/nginx/vhost.d
      #      - ./vhost.d/default_location:/etc/nginx/vhost.d/default_location:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - logs:/var/log/nginx:rw
    #      - ./nginx.tmpl:/app/nginx.tmpl:ro # custom nginx.tmpl
    networks:
      - auto-reverse-proxy-global-network
      - letsencrypt-local-network

  acme-companion:
    restart: always
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${DEFAULT_EMAIL:-webmaster@localhost}
      - DEBUG=${DEBUG:-false}
    networks:
      - letsencrypt-local-network

volumes:
  conf:
  acme:
  vhost:
  html:
  dhparam:
  certs:
  logs:


networks:
  auto-reverse-proxy-global-network:
    external: true
  letsencrypt-local-network: