version: "3.9"
services:
  demo:
    restart: always
    image: "nginxdemos/hello:latest"
    container_name: demo
    ports:
      - "${HOST_PORT:-80}:80"

networks:
  default:
    external: true
    name: l_shared-network